### ISSUE TITLE
Having trouble with this plugin to build out my 'contact' page

### ISSUE THREAD

**Issue by webprojay** [rupok/essential-addons-for-elementor-lite#208]
This plugin is "breaking" my elementor ability.

I am trying to change the form on my contact page and when I have this plugin on, I get the following message.

![screen shot 2019-03-06 at 12 35 45 pm](https://user-images.githubusercontent.com/48292987/53901246-8532e080-400c-11e9-863d-750c7757073d.png)
Only happens when this plugin is turned on

Problem disappears when I turn the plugin off.

But, then I can't do anything with the form I created.

I'm at a standstill here, any help would be appreciated!

Thanks,

J

**Comment by sabuz** [comment]
Hello there,

"The preview could not be loaded" error sometimes is also caused because of a site having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://prnt.sc/le9poi

You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours.

Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

Let me know if this solves your issue or not.

Thank you.

**Comment by webprojay** [comment]
Hello,
I ended up erasing and replacing the theme with a new version because it
was a brand new website.  I will keep your fix in mind should I need it in
the future.  Thanks for your reply! -J

**Comment by sabuz** [comment]
@webprojay We haven't actually heard back from you. I hope your issue was fixed. So, I'm closing this ticket for now. Please feel free to reopen it if you still have any issue!
