### ISSUE TITLE
Updating plugin causes redirect to eael settings page

### ISSUE THREAD

**Issue by keebarber** [rupok/essential-addons-for-elementor-lite#326]
Updating to latest version 3.0.3 (Lite) and 3.0.4 (Pro) causes a redirect back to the Essential Add Ons Settings page from the first link clicked on after updating. This happened after updating to 3.0.2 and 3.0.3 respectively, yesterday as well and has happening on multiple sites. 

E.g. After updating, clicking on 'Dashboard' link redirects back to EAEL settings page. Other links work, but from then on, clicking on the 'Dashboard' link always redirects back to EAEL settings page.
![ScreenRecording20190604at8](https://user-images.githubusercontent.com/30059083/58882991-8cb96280-86ab-11e9-9fd8-3a1c02fa88aa.gif)

**Comment by sabuz** [comment]
@keebarber thanks for reporting this issue, we're solving within very short time...

**Comment by clickharder** [comment]
I have this problem too.  After update, my sub directory sites are no longer accessible when logged in because it keeps redirecting the the settings page.  What is worse, is the link is to an invalid page so I get a "file not found error".  This happens because it tries to redirect to the settings page outside of the wp-admin path.  Either way, it would be nice if it didn't hijack every attempt to view a page and send to the settings page.

**Comment by Donna59** [comment]
Hi, the same here when I create a new page called 'animaties" with elementor I get this when I watch the page https://www.adonnadesign.nl/animaties/admin.php?page=eael-settings 
So this is directing to a 404 page and when I create a redirect it does not work at all. This happend after updating today......

**Comment by lukecav** [comment]
Happened on a site today.
