### ISSUE TITLE
Load More Button EA Post Grid

### ISSUE THREAD

**Issue by endtoosee** [rupok/essential-addons-for-elementor-lite#379]
Hi.. I Want to report a bug on Essential Addons for Elementor version 3.2.1
Just know today that Load More Button on EA Post Grid does not working anymore, please tell me how to fix it.
Thanks..
*Sorry for my english

**Comment by newsensesThomas** [comment]
Having the same problem on several client pages, maybe I can give you some hints...

It only happens if you have more than one Post Grid on your page. If it happens with only one Post Grid, I am quite sure you can fix it by clearing the Essential Addon Cache.

The Problem has its origin in the PostGrid Definition in Javascript. I explored it a bit, but it took too much time to follow through as it is not my code, and I guess the Devs can fix it a lot faster. 

```
var PostGrid = function ($scope, $) {
	
	var container = $('.eael-post-grid-container').eq(0),
		$options   = container.data('post_grid_options'),
		$settings = container.data('post_grid_settings');

	...
```

I guess this is the main problem: Every Post Grid after the first Post Grid gets mistakenly initialized with the IDs / Options / Settings from the first Post Grid. Therefore only the first Post Grid works and receives events (but with errors, as there are too many event Listeners tied to it).

@rupok Maybe this helps for a fix?
