### ISSUE TITLE
Elementor Editing section stuck in infinite load since installation

### ISSUE THREAD

**Issue by brandonxgilliam** [rupok/essential-addons-for-elementor-lite#386]
Hello,

Ever since I installed and activated the plugin the Elementor Editing section (specifically the element selection page) is stuck in infinite load since installation. 
Help would be much appreciated

**Comment by GitMubarak** [comment]
Hi there,
Well, the 'Elementor getting Stuck' error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://prnt.sc/le9poi
You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:
define('WP_MEMORY_LIMIT', '512M');
You would find the wp-config.php file under your WordPress directory.
You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/
Let me know if this solves your issue or not. If it doesn't, you can check for plugin conflicts by deactivating all the plugins except for Elementor and Essential Addons.
If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.
Thank you

**Comment by sabuz** [comment]
Closing the issue due to inactivity for long time. Feel free to reopen if you still facing issues.
