### ISSUE TITLE
Problem with Version 3.5.1

### ISSUE THREAD

**Issue by florcalvet** [rupok/essential-addons-for-elementor-lite#414]
Hi.
I'm having problems vith v 3.5.1, it stay loading in Elementor and i cant edit.
¿where can i download the v 3.2.1? Im using this in other website and its ok.
Thks

**Comment by GitMubarak** [comment]
Hi there,
Well, the 'Elementor getting Stuck' error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://prnt.sc/le9poi
You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:
define('WP_MEMORY_LIMIT', '512M');
You would find the wp-config.php file under your WordPress directory.
You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/
Let me know if this solves your issue or not. If it doesn't, you can check for plugin conflicts by deactivating all the plugins except for Elementor and Essential Addons.
If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.
Thank you.
