### ISSUE TITLE
Modal Popup

### ISSUE THREAD

**Issue by viniciusmaroli** [rupok/essential-addons-for-elementor-lite#444]
Hi, After I updated to WP 5.32 I am having problems with the Modal Popup, when I choose the icon for the button and no text, in the Elementor editor I can see it normally. But on the actual page the icon disappears and I can only click it when I hover from it

**Comment by shamserSuzon** [comment]
Hi, there,

Sorry to hear about the inconvenience. Can you please try doing this following: To regenerate assets, you can go to wp-admin -> Essential Addons then, switch to the ‘Tools’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://prnt.sc/pvozsx

Also, make sure to Regenerate Files from wp-admin -> Elementor -> Tools as well. Then, check back. Let me know how it goes. 

If it doesn't help then please, share the page URL where you are using the Modal popup and also kindly mention the location of the button in your page so that I can find that quickly.

Thank you.
