### ISSUE TITLE
Contact Form 7 for Elementor  / Contact form overlapping issue when sending a message

### ISSUE THREAD

**Issue by JerryAsamao** [rupok/essential-addons-for-elementor-lite#448]
| the "sent message" info is first pushing down but then still overlapping the back to home as seen in the screenshot. EA Contact form 7 is used... Any idea how to solve it in a way that the back to home txt can still stay there..? (I already adde top margin to the link text)

![Contact form before error](https://user-images.githubusercontent.com/60492946/73502957-f6b91180-43ca-11ea-9c8f-ded781a0ed16.png)
![Contact form before error](https://user-images.githubusercontent.com/60492946/73502972-fd478900-43ca-11ea-9b89-0e46d56985ee.png)

**Comment by shamserSuzon** [comment]
Hi there,

I am not clear enough about your query actually by your given screenshot. Could you please, explain/clarify a bit more? Thanks.

**Comment by JerryAsamao** [comment]
Hello. As soon as you hit send, the "message sent button" overlaps the back
to home button (text) .. That's it.  It's the

**Comment by shamserSuzon** [comment]
Please, share the page URL where you are using this contact form. I will check and try to get back to you ASAP with a solution. Thank you.

**Comment by JerryAsamao** [comment]
https://carlosdennis.com/contact-form-cds/

Thank You

**Comment by shamserSuzon** [comment]
Hi there,

I have tried a few CSS tricks but it didn't work indeed because the 'back to home' text is positioned beside the 'SEND' button with a minus margin and the validation/success messages are generating dynamically/based on a trigger. They are not displayed initially.  So, it will not be possible to fix now.

I hope you understand. Thank you.
