### ISSUE TITLE
my elementor is always in loading page after i install EA 

### ISSUE THREAD

**Issue by alyssageraldine** [rupok/essential-addons-for-elementor-lite#456]
My elementor is always staying in loading page since I install EA. once i tried to uninstall EA, my elementor worked fine again. then i tried to reinstall EA, and the problem keep appearing, same with the beginning. so i can't use Elementor if I install EA because it always stays in loading page and i cant click anything afterall.

**Comment by shamserSuzon** [comment]
Hi there,

Well, the 'Elementor getting Stuck' error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://prnt.sc/le9poi

You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

Let me know if this solves your issue or not. If it doesn't, you can check for plugin conflicts by deactivating all the plugins except for Elementor and Essential Addons.

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Thank you.
