### ISSUE TITLE
Elementor widget panel has the continuously spinning "Loading" icon when activated on my server with https

### ISSUE THREAD

**Issue by KreativeNerd** [rupok/essential-addons-for-elementor-lite#485]
Please am having issues after activating this plugin. My Elementor widget panel has the continuously spinning "Loading" icon when activated on my server with https. You can contact me on www.techguides.com.ng or onyejefucollins@gmail.com . Thanks

**Comment by khan-rafin-ahmed** [comment]
Hi @KreativeNerd,

Well, the 'Elementor getting Stuck' error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://prnt.sc/le9poi

You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

Let me know if this solves your issue or not. If it doesn't, you can check for plugin conflicts by deactivating all the plugins except for Elementor and Essential Addons.

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Thank you.
