### ISSUE TITLE
Assential addons fails to open tools in elementor

### ISSUE THREAD

**Issue by nmfa2013** [rupok/essential-addons-for-elementor-lite#487]
Good afternoon,
I installed Essential Addons for elementor but I can't get the tools in the elementor edit window.
Can you help me realize the error?
I send an attached pdf with print screen.
thanks
[Doc1.pdf](https://github.com/rupok/essential-addons-for-elementor-lite/files/4504503/Doc1.pdf)

**Comment by khan-rafin-ahmed** [comment]
@nmfa2013,

Hi there,

Well, the 'Elementor getting Stuck' error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://prnt.sc/le9poi

You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

Let me know if this solves your issue or not. If it doesn't, you can check for plugin conflicts by deactivating all the plugins except for Elementor and Essential Addons.

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Thank you.
