### ISSUE TITLE
Breaking the site

### ISSUE THREAD

**Issue by joao-emidio12345** [rupok/essential-addons-for-elementor-lite#491]
The plugin is breaking my site, taking it off the air and it is extremely important for the site because it occupies a large part of it.

**Comment by rupok** [comment]
Hi @joao-emidio12345 could you provide a bit more information so we can help? Did you see any error message? 
Are you using the latest version of Elementor?

**Comment by joao-emidio12345** [comment]
Hi, there is no error message but the whole site goes down when only this
plugin is activated, if I disable it the whole site will work again. I'm
using Elementor version 2.9.8

Em qua., 29 de abr. de 2020 às 08:32, Nazmul H. Rupok <
notifications@github.com> escreveu:

**Comment by khan-rafin-ahmed** [comment]
@joao-emidio12345,

Hey could you please contact our support here: https://wpdeveloper.net/support/new-ticket/

It's really difficult to say what happened on your end without investigation. Please provide us admin access of your website (along with FTP access) in the support ticket so that we can investigate and resolve this issue for you.

Thank you.
