### ISSUE TITLE
Install of Essential-Addons Causing Issues

### ISSUE THREAD

**Issue by jar-gitme** [rupok/essential-addons-for-elementor-lite#493]
After adding the plug-in "**essential-addons-for-elementor-lite**", the **Elementor Page Builder** plug-in freezes when attempting to edit page.

![Elemenator Editor](https://user-images.githubusercontent.com/64930612/81231585-3f72fe80-8fa8-11ea-9bb2-847ddf94dc09.png)

**Comment by khan-rafin-ahmed** [comment]
@jar-gitme,

Hi there,

Well, the 'Elementor getting Stuck' error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://prnt.sc/le9poi

You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

Let me know if this solves your issue or not. If it doesn't, you can check for plugin conflicts by deactivating all the plugins except for Elementor and Essential Addons.

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Thank you.

**Comment by jar-gitme** [comment]
Thank you for the reply.

After increasing the memory to 512M, the issue remained, however, deactivating plugins one at time, revealed the "Ninja Forms" was causing a conflict. I am surprised this issue arose given the information provided in the following Youtube video -

https://www.youtube.com/watch?v=Lzxd6vNVcaE
