### ISSUE TITLE
Essential addons-pro  no longer works and takes down the elementor page builder

### ISSUE THREAD

**Issue by adrian65-6024** [rupok/essential-addons-for-elementor-lite#528]
Stopped working yesterday. Ran troubleshooter on the staging site  and disabled all, including theme, except for elementor and essentials. Pro and lite versions of each. 

Elementor lite + pro and Essentials Lite + pro will work. However, the page builder fails to load at all ( spinning wheel) once woocommerce is activated. 

Narrowed this down to the esssentials pro add-on. Can recover the page builder with woocommerce if essential pro is deactivated.

Also discovered the same issue has now appeared on the live site. Had to deactivate the pro version there too.

**Comment by abid112** [comment]
Hi @adrian65-6024 ,

Well, the Elementor getting Stuck(Spinning wheel) error is normally caused due to a website having low memory. You can check your memory limit by navigating to wp-admin -> Elementor -> System Info. Check out this screenshot: https://prnt.sc/le9poi

You need to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');
You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

Let me know if this solves your issue or not. 

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Thank you.

**Comment by adrian65-6024** [comment]
Yes thanks re the memory setting. The elementor side menu for the page builder does now load albeit alittle slower All dynamic elements are disabled as a work around
